### ISSUE TITLE
Extensions for rendering & UI

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/react-client#1096]
We should discuss if we ever want to support some form of official extensibility for the client. There were two requests relating to that in the past:

- https://github.com/hedgedoc/hedgedoc/issues/569 asks for custom editor buttons. I would add to the request custom buttons/links in the navbar, e.g. to link to the homepage of the organization.
- https://github.com/hedgedoc/hedgedoc/issues/20 asked for extensions of the rendering process. We already have that issue in this repo as https://github.com/hedgedoc/react-client/issues/438, which got merged into https://github.com/hedgedoc/react-client/issues/360. But #360 only talks about an internal system. What about external plugins?

**Comment by DerMolly** [comment]
An internal extension api is implemented see #360, but we don't have any plans to make it publicly available. Therefore this issue will be closed.
