### ISSUE TITLE
Feature request: Text Replace

### ISSUE THREAD

**Issue by jnnkB** [hedgedoc/react-client#1098]
**Is your feature request related to a problem? Please describe.**
I often need to change the same thing in a document in different places.

**Describe the solution you'd like**
A replace feature. Preferably allowing regular expressions. 

**Additional context**
Currently I have to copy all content into an text editor, do the replace there and copy the new content back into HedgeDoc.

**Comment by ErikMichelson** [comment]
This is already implemented. Just set the cursor inside the editor and press <kbd>Ctrl</kbd> + <kbd>H</kbd>.

**Comment by ErikMichelson** [comment]
Nevertheless, this should be documented (hedgedoc/hedgedoc#713).

**Comment by jnnkB** [comment]
Pressing <kbd>Ctrl</kbd> + <kbd>H</kbd> only deletes the character before the cursor. Since I'm currently on a macOS I also tried <kbd>command</kbd> + <kbd>H</kbd> which didn't work either. 

I tried it on [ui-test.hedgedoc.net](ui-test.hedgedoc.net) using Sublime keybindings.

**Comment by mrdrogdrog** [comment]
I tested the Ctrl+H shortcut on ui-test.hedgedoc.org and on demo.hedgedoc.org. I also tested it on my macbook with Cmd+H. Worked as well.

**Comment by jnnkB** [comment]
My fault. Seems to work for me too. Must have done something wrong with the focus. So thanks a lot and sorry for bothering you.
