### ISSUE TITLE
Editor Feature Discussion: Rendered View with editable row

### ISSUE THREAD

**Issue by RayMacLewis** [hedgedoc/react-client#1114]
**What is your opinion on a "Rendered View with editable row"?**

I am not fully sure if what I suggest is possible to implement in a user friendly way. But I would like to hear your opinions on it:
I really like the rendered markdown view as it give a great readability to my notes. But as often as I read them I also want to add minor changes to it. For this I often have to change to the full editor mode to see where to put my changes to.

I would love to see a feature that shows me a fully rendered note but when I click on a text row for example it would pop up a single row editor below the rendered text. What do you think about a feature like this? Where might this feature be problematic?

Like I said, I'm not sure yet if that would really be a great feature but I think it might have some potential. Looking forward to your opinions.

Ray

**Comment by RayMacLewis** [comment]
Example:
![image](https://user-images.githubusercontent.com/22128092/111691585-c29eeb00-882e-11eb-9c3a-6778fe1f463c.png)

**Comment by DerMolly** [comment]
With the current technical implementation of HD2 this won't be possible.
