### ISSUE TITLE
starting with `yarn start:for-real-backend` results in error: `The task 'Load config' failed.` due to CORS errors

### ISSUE THREAD

**Issue by zeigerpuppy** [hedgedoc/react-client#1162]
**Description**

Starting a development environment with backend on port 3000 and frontend on 3001 results in CORS errors:

Hedgedoc warns that `The task 'Load config' failed.` and web console shows the following errors:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/api/v2/config. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/api/v2/config. (Reason: CORS request did not succeed).
TypeError: NetworkError when attempting to fetch resource.
```

**To Reproduce**
1. build backend with `yarn install`
2. start backend with `yarn start:dev`
3. build frontend with `yarn install`
4. start frontend with `yarn start:for-real-backend`
5. navigate to http://localhost:3001

**Expected behavior**

Hedgedoc should load but fails due to CORS errors

**Your Setup (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox 78.9.0
 - HedgeDoc version
     - server - latest from github - commit ee5a587bcc0a1c4ac788d0446e93bd725ac46f5b
     - client - lasest from github - commit 8b0c60c4aaf6502caac66ab8851dcc6f515e4554

**Additional context**

I have tried adding some CORS variables in backend `.env` file, but it hasn't made any difference:

`.env` file:

```
# SPDX-FileCopyrightText: 2021 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: CC0-1.0

HD_DOMAIN="http://localhost"
HD_MEDIA_BACKEND="filesystem"
HD_MEDIA_BACKEND_FILESYSTEM_UPLOAD_PATH="uploads/"
HD_DATABASE_DIALECT="sqlite"
HD_DATABASE_STORAGE="./hedgedoc.sqlite"

# CORS options
HD_CSP_ENABLE=false
HD_CSP_REPORT_URI="http://localhost:3001"
```

**Comment by mrdrogdrog** [comment]
Neither the backend or the frontend are ready to be used together. This is not supposed to work right now.

**Comment by DerMolly** [comment]
But thank you for the issue anyway. We were already aware. In fact a fix for this already was in a local branch on my machine.
