### ISSUE TITLE
Create new note with pre-filled-content from url query parameter

### ISSUE THREAD

**Issue by jfowl** [hedgedoc/react-client#1234]
https://github.com/hedgedoc/react-client/issues/90#issuecomment-831905553_
->

hedge.doc/new?content=...

When creating a new pad, allow content to be passed in via a query parameter. This would be limited to ~1500 chars because of url limits and encoding bloat, but I assume this would not be that hard to implement ( ala if (queryParams.content && note.content.length == 0) note.content = queryParams.content)

This would be similar to mailto: links which can also contain content.

Use case:

- Provide button on website for students to create a new pad with pre-filled checklist and task to do. (O-Phase: Checkliste "Was sollte ich vor dem Vorlesungsbegin getan haben")

**Comment by mrdrogdrog** [comment]
I don't see why you need a query parameter if you can use the proposed template system in #90

**Comment by jfowl** [comment]
I thought this might be easier to implement than a real template system. This also would not need any interaction with the server, e.g. template urls could be generated on the fly without needing to call APIs.

**Comment by ErikMichelson** [comment]
As I wrote in #90, there is an API endpoint that allows to POST markdown content into a new pad. Having the possibility to accept query parameters can result in security issues. Imagine someone mentions HedgeDoc on its blog post and links to an instance with a link like `/new?content=[Click here to save your note](https://malicioous.example.com)`.

**Comment by jfowl** [comment]
@ErikMichelson I do not consider this risk to be too high, because by default I can see the real link in the editor. Also I could just link to an existing pad with a malcious link, which should not look much different to a new pad with content.

Would any of you oppose this feature if I were to implement it?

**Comment by mrdrogdrog** [comment]
Well. Feel free if you want. But I would wait until the editor code base is a bit more stable.
