### ISSUE TITLE
Tags: alphabetic sorting

### ISSUE THREAD

**Issue by kleineLoesungen** [hedgedoc/react-client#1338]
**Which part of the project should be enhanced?**
Personal Landing Page at filtering section

**Describe the solution you'd like**
The dropdown field is unsorted. For better and faster results I would suggest a alphabetic sorting of displayed names/tags 

**Describe alternatives you've considered**
None 

**Additional context**
Thanks for your great work

**Comment by ErikMichelson** [comment]
When the tag picker is re-done for 2.0 (#1203), alphabetic sorting should be added as well.
