### ISSUE TITLE
Tabular history view that allows me to Ctrl+F through title notes

### ISSUE THREAD

**Issue by d33tah** [hedgedoc/react-client#1472]
First of all, thanks for working on HedgeDoc! It's a truly wonderful platform.

I use Hedgedoc in multiple organizations as a way to store unorganized information - kind of like a pre-wiki stage, when I need to sketch up my thoughts. Sometimes one file¹ is just too few because of how linear it is and this is when I start next files. Thing is, it's too easy to get lost in multiple files because the current history view is lacking.

**Describe the solution you'd like**

A button that allows me to switch from this:

![image](https://user-images.githubusercontent.com/295322/129712597-5e0a9afd-6353-4942-bd63-5e58cdeaf8cf.png)

To a table-based view where ideally I can also control page size (it's already twelve on this instance and the list is growing) and Ctrl+F across all of my titles.

**Describe alternatives you've considered**

...building my own application that connects to the database and renders such a view? Interfacing via API? I feel that this most belongs in the front-end.

**Additional context**

¹ Or however it's called in English. Pardon me, I'm using a Polish description of Hedgedoc.

**Comment by ErikMichelson** [comment]
As shown above, the tabular history page is implemented. For changing the number of notes per page, I opened #1764.
