### ISSUE TITLE
Import brand icons for Element and Discourse

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#154]
**Which part of the project should be enhanced?**
The landing page footer.

**Is your enhancement request related to a problem? Please describe.**
Fork awesome doesn't provide icons for element or discourse.

**Describe the solution you'd like**
We could import the icons as svgs into our project and add them to the footer.

**Describe alternatives you've considered**
Using the fork awesome replacement icons.

**Comment by SISheogorath** [comment]
I recommend to open an issue in the fork-awesome project: https://github.com/ForkAwesome/Fork-Awesome/issues

There is a matrix icon, I just think it sometimes looks imperfect because the square bracket are a bit thin.

**Comment by mrdrogdrog** [comment]
We could replace the riot link with `https://matrix.to/#/!ybaSlrrMNLeuoQuUuR:matrix.org`. That's the way to go now. Then we could replace the icon with the matrix icon, that is already included.

**Comment by mrdrogdrog** [comment]
https://github.com/ForkAwesome/Fork-Awesome/issues/243

**Comment by SISheogorath** [comment]
The reason for the riot instead of matrix.to link down there is mainly to make it a bit easier for people who are not into the ecosystem yet. I never considered matrix.to a rather useful webpage for people who aren't already aware of how matrix works.

Even when we use the matrix icon, I think we could use the riot link there.

**Comment by mrdrogdrog** [comment]
A PR for the Riot icon is already opened. https://github.com/ForkAwesome/Fork-Awesome/pull/232

**Comment by DerMolly** [comment]
I'd suggest leaving this issue open until we can use the new fork awesome icons

**Comment by DerMolly** [comment]
This issue is irrelevant because we will use another icon font see https://github.com/hedgedoc/react-client/issues/2430
