### ISSUE TITLE
Do we want to have a seperate area for pinned history entries?

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/react-client#158]
**What is your question?**
Should Pinned History Entries be separated from the normal entries above? Maybe even on each page of pagination?

**Comment by ccoenen** [comment]
for me, the current model is fine. I would not be opposed to a seperate list, either.

**Comment by ErikMichelson** [comment]
Pinned entries are currently always the first entries of the history / recent notes overview, therefore they're easy to reach. Adding a separate section for pinned entries on each page of pagination just decreases the visibility for the non-pinned notes while not having major benefits. I therefore suggest to no implement a separate area for pinned notes.

**Comment by DerMolly** [comment]
That's a good point I'll close this issue then.
