### ISSUE TITLE
Clickable links in editor

### ISSUE THREAD

**Issue by heinrichreimer** [hedgedoc/react-client#1607]
**Is your feature request related to a problem? Please describe.**
I can't click links in the Markdown editor.

**Describe the solution you'd like**
Many editors offer opening a link (web or email) by clicking on it in the editor while holding `Cmd` or so.

**Describe alternatives you've considered**
Alternatively one can simply open the document preview

**Additional context**

**Comment by mrdrogdrog** [comment]
Duplicate of #951

**Comment by heinrichreimer** [comment]
Sorry for the duplicate :see_no_evil:
