### ISSUE TITLE
Replace React-Scripts with Next.JS

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#1623]
**Which part of the project should be enhanced?**
The used React-Framework

**Is your enhancement request related to a problem? Please describe.**
Right now we use react-scripts as framework, provider for webpack config and default plugins. 
I propose that we switch to [next.js](nextjs.org).
Some reasons:
  - CRA's update cycle is slow. They're still on webpack 4.
  - [CRA is only halfway alive](https://github.com/facebook/create-react-app/discussions/11086)
  - [Next.JS supports server side rendering out of the box](https://nextjs.org/docs/basic-features/data-fetching) 
  - [Next.JS easily integrates into our backend without much custom code.](https://nextjs.org/docs/advanced-features/custom-server)

**Describe the solution you'd like**
Use next.js

**Describe alternatives you've considered**
Snowpack. But that crashes with our code with some cryptic error messages.

**Comment by DerMolly** [comment]
This sounds reasonable to me. Especially since nextjs has a good chance to be maintained in the long run. Not sure if the same can be said about snowpack…
