### ISSUE TITLE
State of the rewrite - is it usable?

### ISSUE THREAD

**Issue by xeruf** [hedgedoc/react-client#1712]
**What is your question?**

The timeline states the release for HedgeDoc 2.0 for 2021, which is almost over.
The Readme does not mention the current state of this frontend.
Can it already be used, i.e. is it alpha-level?
What are the differences to version 1?
Please add some information regarding that.

**Comment by mrdrogdrog** [comment]
Hallo,

> The timeline states the release for HedgeDoc 2.0 for 2021, which is almost over.
That's only a tentative release date. Thanks for the hint. We'll change that to 2022 (or to "when it's done").

> The Readme does not mention the current state of this frontend.
> Can it already be used, i.e. is it alpha-level?
We could write "Still in development" into the README but I'm not sure if that would be helpful.
Our current state of the frontend is deployed to https://ui-test.hedgedoc.net/ . But this is only the frontend. It contains only mocked data and no data saving. We'll try to connect frontend and backend soon.
We really have no idea when we're going to release a working version. We (The HedgeDoc core dev team) are working on this in our free time. So we can only make progress if you have time for that.

> What are the differences to version 1?
Some of the differences can be found in the [changelog](https://github.com/hedgedoc/react-client/blob/main/CHANGELOG.md)

**Comment by xeruf** [comment]
Thank you, I appreciate all the effort you put in as an open-source developer myself :)
A rough ETA helps, so I can assess whether it is worth to wait or setup v1 in the meanwhile.

Btw, the changelog links to
https://hedgedoc.org/faq/
which does not exist.

Also, [added PlantUML support](https://github.com/hedgedoc/react-client/issues/324) seems to be missing in the changelog

**Comment by ErikMichelson** [comment]
I'd recommend setting up the current version 1.9.2 in the meanwhile. We'll provide some kind of upgrade-tool when releasing version 2.0 to make sure that the effort of upgrading is as easy as possible.

Regarding the FAQ link: It seems we've forgotten to update the link in the changelog. The FAQ is now hosted on our docs page: https://docs.hedgedoc.org/faq/

Regarding the missing changelog entry: Feel free to create a PR for this. However, prior to release, we'll be looking through the changelog anyway again.

**Comment by mrdrogdrog** [comment]
Fixed the changelog in https://github.com/hedgedoc/react-client/pull/1769

**Comment by DerMolly** [comment]
After the merge of frontend and backend, this issue, that was kept open as information about the react-client repo, is not necessary anmore.
