### ISSUE TITLE
Change asciinema embedding method

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/react-client#1723]
**Description**
Asciinema used embed-iframe URLs previously. They dropped suppport for them and now the only way for embedding a video is with a custom js script from them.

**Additional context**
We possibly could re-use our GitHub Gist strategy for this.

**Comment by mrdrogdrog** [comment]
Additional info: he refers to the gist strategy BEFORE gist provided an embeddable URL.
We used an iframe in which we injected a basic html structure that loaded the script url.

I would like to NOT do that again because we have NO cors protection while doing this.

**Comment by ErikMichelson** [comment]
In that case, I'd vote for dropping asciinema.

**Comment by mrdrogdrog** [comment]
me too.

**Comment by mrdrogdrog** [comment]
@DerMolly ?

**Comment by DerMolly** [comment]
Drop it, then
