### ISSUE TITLE
Deduplicate delete modal

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#1731]
**Which part of the project should be enhanced?**
Note deletion modal

**Is your enhancement request related to a problem? Please describe.**
Right now we have two implementations of the "do you want to delete the note" modal in the history and in the editor sidebar. This could be deduplicated.

**Describe the solution you'd like**
Deduplicate the note deletion modal.

**Describe alternatives you've considered**
Maintain two components that do the same.

**Additional context**
Maybe it's a good idea to restructure our folder structure a bit, so it's not only sorted by "common" and "per page" but a bit more by purpose.

**Comment by ErikMichelson** [comment]
This reminds me of: https://github.com/hedgedoc/react-client/blob/e40e9d89c88a5bc057b01c628b06acbf53d5c920/src/components/landing/pages/history/common/entry-menu/dropdown-item-with-deletion-modal.tsx

**Comment by mrdrogdrog** [comment]
@ErikMichelson  Exactly
