### ISSUE TITLE
Allow changing the amount of entries per history page

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/react-client#1764]
**Which part of the project should be enhanced?**
History page -> pagination

**Describe the solution you'd like**
Having a selector to choose how many cards/table entries to display per history page.

**Describe alternatives you've considered**
Keep fixed values unconfigurable

**Additional context**
#1472

**Comment by mrdrogdrog** [comment]
Closed in favor of https://github.com/hedgedoc/react-client/issues/2116
