### ISSUE TITLE
Remove Focus from button when they open a modal

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/react-client#1766]
**Description**
A button that opens a modal still has focus, when the modal is closed.

This can be observed with the 'Editor settings' button.

**Expected behavior**
If a button opens a modal, it should lose focus, when the modal is closed.

**Screenshots**
![be2fa9ef-4312-4918-af98-d4e13c5d267a](https://user-images.githubusercontent.com/3978662/148945234-0f06b422-4c37-4b57-ba3c-6e4dd6a66cdd.png)

**Comment by DerMolly** [comment]
Probably releveant https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/blur

**Comment by ErikMichelson** [comment]
Instead of just blurring, the focus should be set back to the element before the button action.
For example when clicking a toolbar button while having text selected, the focus should return to the selected text after the button click.

**Comment by mrdrogdrog** [comment]
That is already done in the codemirro 6 branch.
