### ISSUE TITLE
Add unit tests for markdown extensions

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#1785]
**Is your feature request related to a problem? Please describe.**
Most of our markdown extensions aren't tested. Some of them are covered with e2e test suites.

**Describe the solution you'd like**
Unit test the markdown extensions.

**Describe alternatives you've considered**
Use e2e tests for the extensions. The downsides are that e2e tests take way to long for all the possibilities. They should only be used to test a combination of the features.

**Comment by DerMolly** [comment]
duplicate of https://github.com/hedgedoc/hedgedoc/issues/2909
