### ISSUE TITLE
Reimplement settings dialog

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#1858]
**Is your feature request related to a problem? Please describe.**
#1787 removed the editor preferences dialog. This is done because CodeMirror 6 doesn't have one global config object anymore. The new way to go is to configure the modules of the editor themself. 
We decided that it would be better to remove the dialog instead of adjusting it and create a complete new one.

**Describe the solution you'd like**
A new settings dialog with config options for:
 - [ ] Sync scroll mode
 - [ ] Ligatures
 - [ ] Table autoformatting when pasting
 - [ ] Spellcheck

**Describe alternatives you've considered**
Convention over configuration.

**Comment by ErikMichelson** [comment]
Instead of a settings dialog, one could think of a dedicated settings page.

**Comment by mrdrogdrog** [comment]
I don't think that a dedicated page would be useful. That are unnecessary page reloads for UI settings.

**Comment by mrdrogdrog** [comment]
Solved with 4e18ce38f3bfe9571ebf2a203010522cf3576768
