### ISSUE TITLE
Keyboard & Mouse Shortcut Representation in Markdown extension

### ISSUE THREAD

**Issue by ethereal-engineer** [hedgedoc/react-client#1959]
**Is your feature request related to a problem? Please describe.**

Recently I have been using HedgeDoc 1.x to write cheatsheets for the 3D modelling package Blender. In order to have the most presentable, clean aesthetic, I have been using this notation:

Shortcut | Name | Example | Description
---------|------|---------|-------------
<kbd>g</kbd>| grab |`g x 10` | grab and move forward along the x axis 10 units
<kbd>r</kbd>| rotate |`r y 90` | rotate 90 degrees around the y axis

... which looks great when the mouse isn't involved. This is the nicest I could get it looking, whilst still conveying information quickly, in a minimal way:

Key | Function | Notes
----|----------|------
<kbd>ctrl</kbd><kbd>shift</kbd><kbd>x</kbd> | activate | anywhere in the 3D viewport
<kbd>space</kbd> | cycle through cutting shapes | (once activated - duh)
<kbd>ctrl</kbd>`LMB` | reposition cursor |
<kbd>d</kbd> | toggle cursor depth | use with repositioning the cursor (above)

**Describe the solution you'd like**

What I'd like to see is a way of representing the mouse for documentation such as this. Initially, just a 3-button mouse with the appropriate button emphasised, but it could extend to scroll wheel depiction, dragging, double click action, and more. It would also be nice to have an extension to the ML interpreter so that HTML tags were unnecessary.

**Describe alternatives you've considered**

What I thought would be a cool, more general feature, would be the ability to reference FontAwesome glyphs, and/or Google Material Design glyphs (and hey maybe even Google Fonts) from within a document. Perhaps by defining imports in the YAML section?

**Additional context**

**Comment by mrdrogdrog** [comment]
Hello,

We use https://forkaweso.me/Fork-Awesome/ as our icon lib. You could go to their repo and open icon requests. As soon as they would be included in a release we can use them.

**Comment by ErikMichelson** [comment]
I'm going to close this issue.
As mentioned by @mrdrogdrog you could create the needed icon requests over at ForkAwesome, as we include that as our icon library. We cannot do anything here from our point.
