### ISSUE TITLE
WebSocket communication: List online users

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/react-client#1988]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
The online users sidebar menu should contain the list of currently active users.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by ErikMichelson** [comment]
GUI and redux state methods/types were implemented with https://github.com/hedgedoc/react-client/commit/6d7bd019a3cbe27eef92d44b957d71d89d559784

Only the websocket connection for this is missing yet.

**Comment by mrdrogdrog** [comment]
Fixed in https://github.com/hedgedoc/react-client/pull/2118
