### ISSUE TITLE
.rocks domains do not get auto-linkified

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/react-client#2304]
**Which part of the project should be enhanced?**
The...renderer? auto-linkifier?

**Is your enhancement request related to a problem? Please describe.**
If I add plain links to my Markdown document using TLDs like .de or .com, they automatically are converted into links. The .rocks TLD is not auto-converted:

![image](https://user-images.githubusercontent.com/5023650/185787040-602bfafa-8655-40fb-94c7-87a03e1e514e.png)

**Describe the solution you'd like**
All links with domains from the [public suffix list](https://publicsuffix.org/list/public_suffix_list.dat) should be auto-linkified.

**Describe alternatives you've considered**
Keep the current system that provides a confusing user-experience.

**Additional context**

**Comment by mrdrogdrog** [comment]
Markdown-it uses [linkify-it](https://github.com/markdown-it/linkify-it) for link detection.
This has a function `.tlds()` which allows to set custom tlds. 

If you don't do this then linkify falls back to a built in list.
![image](https://user-images.githubusercontent.com/6124140/185788373-fed8c798-a4e9-4dcb-be2e-bbcf3d85ccad.png)

However. Markdown it doesn't offer a possibility to configure its linkify-it instance.

**Comment by mrdrogdrog** [comment]
So we need to live with it and tell people to use the markdown link syntax or create our own linkify-plugin.

**Comment by DerMolly** [comment]
We could also open an issue / PR with markdown-it enabling the configuration of linkify-it?

**Comment by mrdrogdrog** [comment]
Remove my last sentence. Reading docs helps. 
![image](https://user-images.githubusercontent.com/6124140/185789469-886d2e3c-2acd-4606-9749-27f42d415510.png)

https://markdown-it.github.io/markdown-it/

So. It's possible if we import [tlds](https://www.npmjs.com/package/tlds) and stuff that into linkify after the creation of the markdown-it-instance.
