### ISSUE TITLE
Better UX for the creation of links

### ISSUE THREAD

**Issue by drupol** [hedgedoc/react-client#2365]
Hi,

Here's a proposal to improve the way we create links in HedgeDoc.

### In HedgeDoc 1
When creating a link in HedgeDoc, I select the text of the link, then click the link button, and then I need to select manually the `http://` part that gets added automatically and hit CTRL+V to paste the link.
Question: Is there a way to automatically select the `https://` instead of selecting the `<text>` ? It would be so much faster to create links.

### In HedgeDoc 2
I just tested on [hedgedoc.dev](http://hedgedoc.dev/), and the behavior is different.
When selecting the text to link, the text gets wrapped with [<text>](https://) and the cursor is then placed after the closing parentheses, which is really not convenient. I still need to manually select `https://` and then hit CTRL+V.

If you want to test the proper behavior, try on Github, it implements the perfect UX for creating links IMHO.

Here's what I have in mind:

[![](https://planttext.com/api/plantuml/png/dP9FIyD04CNl-oaUU6a3ck9_seCzA7We8XRnlDbCcgMRtRWpGGlzy6wIAaXFUWbiPdxllPtP9OkEqZKEJ_OpC4wniXKXLD1eE-SGwRqZ5gN4YYFK8YtFytnZfUwACnEQlAPoGsKmUIHjvDGuIrvoovou_FpY-WfAxKykPpUtPhP_POhxTDn4skqVU_8-63oKLaBwhmxr8PG2vlqH7zeBGm8QlQMKorc_NQYVCfCZ8-3G4ABsPMWWz2cm7b8JQD1UfFOV8aKqMuIndcMz7efE9FWi-yOa15VeEFWS1mLiXSbwSARouCVG7gylgxjfh-0nsH5FKskoVOkw7MJvD-9Ha7nGQiwoLiSqk9gOECiM8_VijA41D5ta4A4hIHSOSrSsiY2qvAtVe8ZQR4b6b1mJ9ZxymVx0_ylxA3hvqbRZo0yhJOBhVgkGNTiZmxg654cvrIpKJw-BRg4Ih9Rfarwb-W80)](https://planttext.com/?text=dP9FIyD04CNl-oaUU6a3ck9_seCzA7We8XRnlDbCcgMRtRWpGGlzy6wIAaXFUWbiPdxllPtP9OkEqZKEJ_OpC4wniXKXLD1eE-SGwRqZ5gN4YYFK8YtFytnZfUwACnEQlAPoGsKmUIHjvDGuIrvoovou_FpY-WfAxKykPpUtPhP_POhxTDn4skqVU_8-63oKLaBwhmxr8PG2vlqH7zeBGm8QlQMKorc_NQYVCfCZ8-3G4ABsPMWWz2cm7b8JQD1UfFOV8aKqMuIndcMz7efE9FWi-yOa15VeEFWS1mLiXSbwSARouCVG7gylgxjfh-0nsH5FKskoVOkw7MJvD-9Ha7nGQiwoLiSqk9gOECiM8_VijA41D5ta4A4hIHSOSrSsiY2qvAtVe8ZQR4b6b1mJ9ZxymVx0_ylxA3hvqbRZo0yhJOBhVgkGNTiZmxg654cvrIpKJw-BRg4Ih9Rfarwb-W80)

**Which part of the project should be enhanced?**
When creating links within the editor.

**Comment by ErikMichelson** [comment]
The selection of the link or text after clicking the link button is part of hedgedoc/hedgedoc#2919.
