### ISSUE TITLE
SignInButton links to '/n/login' from notes

### ISSUE THREAD

**Issue by tamo** [hedgedoc/react-client#2445]
If a guest visits a page (e.g. ```/n/features```), the sign-in button navigates to ```/n/login``` instead of ```/login```.

https://github.com/hedgedoc/react-client/blob/cb2ef84655e3000c4cbe453a19662fe1bbaae107/src/components/landing-layout/navigation/sign-in-button.tsx#L37
this should be ```return '/login'``` maybe?

**Comment by ErikMichelson** [comment]
Good catch, however we built the app to avoid absolute paths with a `/` prefix, therefore I'm not sure about your suggested change.

@mrdrogdrog do you want to take a look?
