### ISSUE TITLE
Dark Mode in 2.0 fails in Firefox

### ISSUE THREAD

**Issue by mcnesium** [hedgedoc/react-client#2502]
Follow-up of https://github.com/hedgedoc/react-client/issues/1235#issuecomment-1297106954:

Unfortunately the new dark mode introduced in #2448 doesn't seem to work well in Firefox 106 on Gnome Desktop:

[Screencast from 08.11.2022 17:36:27.webm](https://user-images.githubusercontent.com/476060/200624216-8e39e250-73ca-4696-b664-d3bf8286de11.webm)

At 0:28 I switch to light theme and back to dark at 0:32. 

Please suggest how I can provide more helpful information.

**Comment by mrdrogdrog** [comment]
It does work, but the preferred setting is read only once at the start of the app.

**Comment by mrdrogdrog** [comment]
(at least it does that right now. I guess we never thought about syncing the color scheme after the app has been initialized😅)

**Comment by mrdrogdrog** [comment]
Has been solved with 4e18ce38f3bfe9571ebf2a203010522cf3576768 . Should already be deployed on hedgedoc.dev
