### ISSUE TITLE
New user will see an error on successful registration

### ISSUE THREAD

**Issue by tamo** [hedgedoc/react-client#2524]
On /register, a new user (who has no cookies) will see the message "There was an error while registering your account. Just try it again" on registration, but the account will have been successfully created.

1. Clear your cookies
2. Visit /register and fill in the form
3. Click "Register"
4. No redirection, just an error message ← problem
5. Visit /login and see you can sign in

https://github.com/hedgedoc/react-client/blob/743e066e6458424c757e042df6098d9e7857851e/src/pages/register.tsx#L48
Seems that "GET (backend)/api/private/me" returns "401 Unauthorized" here.

**Comment by mrdrogdrog** [comment]
Seems like the backend isn't setting the session cookie after registering. So it's a backend issue :shrug:
