### ISSUE TITLE
More intuitive /login and /register pages for new users

### ISSUE THREAD

**Issue by tamo** [hedgedoc/react-client#2525]
**Which part of the project should be enhanced?**

login and register pages

**Is your enhancement request related to a problem? Please describe.**

A new user could expect the /register form should be filled with the values she has already input to /login.
My guess is
1. A new user will visit /intro,
2. click the "Sign In" button,
3. fill in the username and password,
4. click the "Register" button,
5. and be surprised or disappointed that she has to fill the username and password again

**Describe the solution you'd like**

I have a couple of ideas.
1. Place the "Register" button differently
The /login page can be something like
```
Sign in via Username
     [Username]
     [Password]
     [Sign In]
       - or -
     [Register]
```
In this way, no one should expect the "Register" button posts the values above

**Describe alternatives you've considered**

2. Copy the data from /login to /register
3. Create another page
The /intro page can have "Register" next to "Sign In"

**Additional context**

The "Register" button on /login is gray now
![image](https://user-images.githubusercontent.com/383537/201529643-af1f7486-8854-4ffa-92d8-149e058e16eb.png)
1. If username and password are empty, the "Sign In" button should be grayed and "Register" can be blue
2. If one of them is filled and the data will be copied to /register, "Register" can be blue
3. If one of them is filled and the data will NOT be copied, both buttons should be gray

**Comment by mrdrogdrog** [comment]
Login and Register will get a new UI that is completely different from the current version.
