### ISSUE TITLE
Add 'nofooter' option for slide presentation mode 

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/react-client#325]
Port of https://github.com/codimd/server/pull/334 for the new frontend.

**Which part of the project should be enhanced?**
The slide presentation mode has a footer with metadata about the presentation that optionally may host disqus. If you scroll down by accident in a presentation, the footer might be irritating.

**Comment by DerMolly** [comment]
The footer is not a part of HedgeDoc 2 anymore, so this can be closed…
