### ISSUE TITLE
Add 'pin'/'favorite' button in the note editor

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/react-client#331]
Currently, it is possible to 'pin' a note in the note history view.
This feature should also be available in the note editor itself.
It seems counter-intuitive to read a note, find it 'pin worthy' and then need to switch to the history view to actually pin it.

The easiest way to add this is probably to add a pin (or favorite star) button in the top taskbar.

This is blocked by #330

**Comment by mrdrogdrog** [comment]
The button is there, but it doesn't work right now.

**Comment by DerMolly** [comment]
I discussed this with @InnayTool and we both think that the functionality of the button needs to be implemented via the websocket.
