### ISSUE TITLE
Reveal.js - Render mode

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#368]
HedgeDoc 1.x has a slide mode (`/p/`). We should reimplement this.

- [x] Editor
  - [x] Switch the preview to slide renderer if the frontmatter tag `type` is set to `slide`
  - [ ] Sync scrolling
- [x] Slide-Page
  - [x] Create a route to a page that shows the slideshow
- [x] Render-Page
  - [x] Create a renderer for slides
  - [x] Merge `BasicMarkdownRenderer` and `FullMarkdownRenderer` and extract everything that is only relevant for documents (`markdown-body`, title-anchors) into a `DocumentMarkdownRenderer`
  - [x] Create `SlideMarkdownRenderer`
  - [x] Add support for HTML comments
- [ ] Add more slide options
- [ ] Speakerview

**Comment by DerMolly** [comment]
some notes:
 - the code from the old frontend https://github.com/hedgedoc/hedgedoc/blob/299301f0fe5bea41b4407bbbc03932fc4dd1c1d3/lib/web/note/util.js
 - https://github.com/webpro/reveal-md#readme a software who does markdown -> reveal.js already
