### ISSUE TITLE
Slides rendered differently to preview

### ISSUE THREAD

**Issue by DougInAMug** [hedgedoc/react-client#404]
Hello! And thanks for all the work so far :bow: 

I thought I would let it be known that the previews of slides (i.e. `type: slide`) do not reflect the rendered slides in presentation mode. Specifically: 
1. the background of previews are white, whereas the background of rendered slides are black: this leads to surprising and sometimes undesired visual presentation 
2. the content in previews appears to be smaller than in rendered slides: text or images that fit in the preview frame often overrun the rendered frame (example: https://demo.codimd.org/OcnQfVA8Rd2uB61dnuIDXw#)

Thanks for reading, happy to do testing :sweat_smile:

**Comment by ErikMichelson** [comment]
The slide preview is now using the same renderer as the slide presentation mode.
It can be tested here: https://hedgedoc.dev/n/slide-example

Sync-scrolling of the slide preview with the editor will follow up.
