### ISSUE TITLE
Feature request: Image placeholders

### ISSUE THREAD

**Issue by Xalaxis** [hedgedoc/react-client#406]
When typing an image element without any source URL, it would be helpful if a placeholder element could be displayed which when clicked allows the user to select an image for upload.

Example syntax: `![Placeholder text]`

**Comment by mrdrogdrog** [comment]
If the url is "placeholder", then don't use the url. Instead use a static image. Sounds easy.

**Comment by mrdrogdrog** [comment]
The only component we'll have to modify is the ImageFrame. 
@ErikMichelson @DerMolly , what do you think?

**Comment by DerMolly** [comment]
I think that can be done. We would also need to change the insertImage function and the tests.

**Comment by Xalaxis** [comment]
For me the "placeholder" functionality is pretty vital.  That way I can go through a whole entry and put `![Loading screen]`, `![Screenshot of item]` and then later be able to see what I wanted to put there and fill them in.

**Comment by Xalaxis** [comment]
Here's how ghost used to handle it - "Add image of <placeholder>":
![image](https://user-images.githubusercontent.com/12937964/90173534-7a9d7e80-dd9c-11ea-990f-9f5aeef98a91.png)

**Comment by mrdrogdrog** [comment]
> I think that can be done. We would also need to change the insertImage function and the tests.

Which insertImage?

**Comment by mrdrogdrog** [comment]
I'm not sure if we should use the use the syntax from ghost, because if we just use the default markdown image syntax (something like `![](placeholder)`), we don't have to change much code. In fact we only have to modify the image frame component that handles the rendering of imgages in the markdown renderer.

**Comment by Xalaxis** [comment]
Oh, I see, you mean `![This is what I want to put here later](placeholder)` like this?  I'd definitely be happy with that, the key thing is being able to make a note for later that gets automagically deleted when I add the image.

**Comment by DerMolly** [comment]
> > I think that can be done. We would also need to change the insertImage function and the tests.

> Which insertImage?

https://github.com/codimd/react-client/blob/8c84ab700597744ea58c4ca41b469c12804642ba/src/components/editor/editor-window/tool-bar/utils.ts#L19-L21

https://github.com/codimd/react-client/blob/8c84ab700597744ea58c4ca41b469c12804642ba/src/components/editor/editor-window/tool-bar/utils.ts#L98-L112

**Comment by mrdrogdrog** [comment]
Well why not? If you select a text and this isn't an url we could just use "placeholder" instead of an invalid url.

**Comment by DerMolly** [comment]
Yeah, but we would need to do that. That's why I mention it here.

**Comment by ErikMichelson** [comment]
This has been implemented with #1666

**Comment by Xalaxis** [comment]
Thanks all!
