### ISSUE TITLE
automatic history upload

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/react-client#41]
if the user has no history on the server, the frontend currently offers to upload a possible localStorage history.

I think it would be a good idea to look in the localStorage to determine if there is something to upload and then do that automatic. Also the localStorage should be cleared after a successful upload.

That would make the process of going from a anonymous user to a user with a profile a bit smoother and doesn't require to see the magic import button at the right moment...

**Comment by SISheogorath** [comment]
I don't think that's a good idea. Why? Imagine you are in a public library, and while they should clean caches and alike after you used a machine there, they don't do this all the time. So when you go to CodiMD, login to your account or sign-up for a new one, you might end up with someone else's notes in your history. Definitely not how it should work out.

**Comment by davidmehren** [comment]
Maybe show a "We found a history in your browser. Would you like to import it?" toast/modal? To make it a bit more prominent than the current button.

**Comment by mrdrogdrog** [comment]
The information that is missing in the first post is:
Our intention wasn't to do that EVERY time. Only if your remote history is empty. But I think a button/modal is the better way.

**Comment by ErikMichelson** [comment]
This has been superseded by the explore page https://github.com/hedgedoc/hedgedoc/issues/994
