### ISSUE TITLE
Better Wiki support

### ISSUE THREAD

**Issue by zeigerpuppy** [hedgedoc/react-client#443]
CodiMD already has the underlying features necessary for using it as a wiki (especially arbitrary named page creation).  There are a couple of minor changes that would make this much easier to use, however:

1. ability to add internal links with the `[[NewPage]]` syntax (currently, a user needs to use `[NewPage](/NewPage)`
2. A way of seeing backlinks (Maybe a left sided TOC like menu on the view mode only would be an option)
3. An editor button for adding wiki links

**Comment by DerMolly** [comment]
Just reading this again…
I'm just thinking, why not use the users history for the autocompletion? In theory there could be more notes, but it seems quite robust for the time being.

**Comment by mrdrogdrog** [comment]
that could work

**Comment by mrdrogdrog** [comment]
I'm going to close this issue because we won't implement wiki features.
For the auto completion I have opened a new issue #958.

**Comment by flancian** [comment]
Hi there! Thank you for this thread. Without meaning to necromance, I wanted to update this issue saying that I've created https://community.hedgedoc.org/t/proposal-wikilinks-support-either-in-core-or-as-an-add-on/836 to discuss possible ways forward for getting some [[wikilinks]] support in HedgeDoc.
