### ISSUE TITLE
Add spell checker

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#479]
**Is your feature request related to a problem? Please describe.**
Codimd 1.6 had a spell checker in the editor, that was able to show misspelled words, but couldn't offer corrections.
The only supported language was english.

**Describe the solution you'd like**
- [ ] Add a fast, code mirror compatible spell checker (maybe https://github.com/cfinke/Typo.js/ ?)
- [ ] Add support for multiple languages
- [ ] Add corrections

**Describe alternatives you've considered**
A banner that says users "buy a dictionary! (link to amazon)"

**Comment by DerMolly** [comment]
Did you investigate how to integrate Typo.js with CodeMirror? All I found was https://github.com/pirtleshell/codemirror-typo#readme and that seems to have no typings (not really a deal breaker as this could easily be added by us).

**Comment by mrdrogdrog** [comment]
I would use https://codemirror.net/demo/lint.html

**Comment by hydrargyrum** [comment]
The [YAML metadata](https://demo.codimd.org/yaml-metadata) supports a `lang` option. It would be good if the spell checker used that option to correct based on the document language.

**Comment by davidmehren** [comment]
I'd love to see support for [LanguageTool](https://languagetool.org/dev), an open-source grammar and style checker. It's available as a SaaS cloud offering and also self-hostable (Java).

**Comment by lkiesow** [comment]
Using LanguageTool as a browser plugin for any input fields works great for most tools and input fields. It would be great if HedgeDoc would just support these browser plugins. That would also allow users to choose whatever service they want to use for this. LaguageTool, Grammarly or whatever they want.

**Comment by ErikMichelson** [comment]
Actually with the usage of CM6 as the editor nowadays, the only thing preventing the usage of LanguageTool or browser native spell checking are the attributes `spellcheck="false"` and `autocorrect="false"` which are set for the CodeMirror container. Removing these attributes seems to work for me without breaking other functionality of the editor.
