### ISSUE TITLE
Allow links in [name=...] syntax

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/react-client#648]
**Description**
This frontend does not allow links inside the name-tag. As 1.6 supports just this, we should fix that.
The minimal example below will not be replaced.

**To Reproduce**
Minimal document:
```markdown
> [name=[Example](//example.com)]
```

**Expected behavior**
The minimal example above (and all other valid cases) will be replaced properly with the name-indicator.

**Additional context**
The problem is the `]` (required for link label) inside a name-tag.
We use the following regex: `/\[name=([^\]]+)]/`
Version 1.6 uses this regex: `/\[name=(.*?)\]/` (thus also allowing empty name-tags)

**Comment by mrdrogdrog** [comment]
> This frontend does not allow links inside the name-tag.
Is there a usecase for this? It looks more like a side effect.

> thus also allowing empty name-tags
Easy solution: Use `/\[name=(.+?)\]/`

**Comment by DerMolly** [comment]
> > This frontend does not allow links inside the name-tag.

> Is there a usecase for this? It looks more like a side effect.

People could use something like this `[name=[@DerMolly)(https://github.com/DerMolly)]`

**Comment by DerMolly** [comment]
I worked on that just now and either I'm not really awake or the purposed regex does not work. Even after trying to build some better regex the quoteExtra MarkdownIt Plugin does not trigger and it get's rendered as 
![image](https://user-images.githubusercontent.com/3978662/95520574-e2043300-09c7-11eb-9cb0-164dc11780cc.png)

**Comment by ErikMichelson** [comment]
@DerMolly That's exactly the problem, why I raised this issue. A quick fix by using the other regex just isn't working. I don't know what exactly is the problem, the only difference is, that the regex in 1.6 was applied to the whole content-string while here being given to the regex plugin.

**Comment by ErikMichelson** [comment]
> People could use something like this `[name=[@DerMolly](https://github.com/DerMolly)]`

That's exactly what I saw in a note I randomly stumpled upon and that raised my inner question if that works in our client.

**Comment by DerMolly** [comment]
@SISheogorath build some better regex `\[name=((?<name>[^\[\]]+?)|\[(?<text>[^\]]+?)\]\((?<url>https?:\/\/\S+?)\))\]`
This matches quite good, but it can't directly be used in `replaceQuoteExtraAuthor`

**Comment by mrdrogdrog** [comment]
Before you ask again @DerMolly: Yes, I'm still on it.

Latest attempt: I'm building a markdown it plugin, that uses regex and markdown-it-rulers.
