### ISSUE TITLE
Try to move external-types

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/react-client#656]
We should try to move as much as possible from `src/external-types` to either the projects repos or DefinetlyTyped.

- [x] abcjs [PR there](https://github.com/paulrosen/abcjs/pull/536)
- [x] emoji-mart
  - unnecessary as of #620 
- [x] flowchart.js [PR there](https://github.com/adrai/flowchart.js/pull/212) | [PR here](https://github.com/codimd/react-client/pull/671)
- [ ] markdown-it-abbr
- [ ] markdown-it-deflist
- [ ] markdown-it-emoji
- [ ] markdown-it-footnote
- [x] markdown-it-front-matter [PR there](https://github.com/parksb/markdown-it-front-matter/pull/12)
- [ ] markdown-it-imsize
- [ ] markdown-it-ins
- [ ] markdown-it-linkify
- [ ] markdown-it-mark
- [ ] markdown-it-mathjax [PR there](https://github.com/classeur/markdown-it-mathjax/pull/12)
- [x] markdown-it-plantuml [PR there](https://github.com/gmunguia/markdown-it-plantuml/pull/28)
- [ ] markdown-it-regex [PR there](https://github.com/tylingsoft/markdown-it-regex/pull/2)
- [ ] markdown-it-sub [PR there](https://github.com/markdown-it/markdown-it-sub/pull/2)
- [ ] markdown-it-sup [PR there](https://github.com/markdown-it/markdown-it-sup/pull/4)
- [x] markdown-it-toc-done-right [PR there](https://github.com/nagaozen/markdown-it-toc-done-right/pull/40) | [PR here](https://github.com/codimd/react-client/pull/665)
- [x] markmap-lib
  - afaik this is not possible to remove as it is needed to function correctly, but it's a reexport anyway so maybe that is okay-ish.

**Comment by mrdrogdrog** [comment]
Please be sure, that
- Every PR includes EVERY possible type, signature and option! For our project it's okay to just use what we need. But if you provide these types to the original project then add everything. Otherwise they're useless because other devs have to complete them for their projects.
- You use `function` instead of lambda consts.

**Comment by DerMolly** [comment]
Most of these were attempted, but many repos did adopt this unfortunatly
