### ISSUE TITLE
Upload images on drag&drop and paste

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/react-client#672]
**Describe the solution you'd like**
As currently implemented in 1.6, an image should be uploaded when it's pasted from the clipboard into the editor or when it's dragged into the editor window.

**Comment by DerMolly** [comment]
add an Overlay with something like "Drop image to upload" to indicate drag and drop fuctionality

**Comment by SISheogorath** [comment]
Alternatively, the mouse cursor could be used for indication (changing it). Depends on whether it should be possible to navigate for the upload inside the doc or not. (This might be related to editor capabilities feel free to explore.)
