### ISSUE TITLE
Fork Awesome preview in emoji picker

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#700]
**Is your feature request related to a problem? Please describe.**
Every fork awesome icon in the emoji picker is displayed by a static default image.

**Describe the solution you'd like**
Add previews for the icons.

**Additional context**
Our [current picker](https://github.com/nolanlawson/emoji-picker-element) doesn't support custom css classes for emojis, which is necessary for fork-awesome.
[The dev of emoji-picker-element doesn't want to support icon fonts that are activated by css classes.](
https://github.com/codimd/react-client/issues/430).
So we have some options:
- Don't show icons
- Choose another picker (pls not)
- Change picker (bad idea, because the dev doesn't want that)
- Include all the SVGs
- Create a single SVG with every glyph.

**Comment by DerMolly** [comment]
Not relevant anymore. See #2430
