### ISSUE TITLE
Idea: Slide improvements

### ISSUE THREAD

**Issue by HerHde** [hedgedoc/react-client#717]
Hey lads,
since I'm working quite often with the slide mode I've got some ideas to discuss and propose:

## Download compiled slides

Add a *Presentation* item to the download menu for offline (or wherever) usage, which outputs the compiled slides

- without the footer
- including assets like
  - CSS
  - JS
  - image assets (or whatever you can upload)
- as an archive

## Editor: Slide options in the toolbar

Add a slide option button to the editor toolbar, opening a dialog to dis-/enable the `type: slide` and other options in the front YAML.
If enabled, show buttons for individual slides in the toolbar, like uploading a background image, adding a fragment, new slide (`---` or `----`) etc.

## Vertical alignment options

Implement an option to set the vertical alignment of a slide, useful for background images and title slides. Example where it would be useful to align the content:
![example](https://user-images.githubusercontent.com/7630662/55307795-7e06c300-5450-11e9-93c8-cb193ca8bfc5.png)
*I think this would be a bit too much, since it is possible through HTML & CSS and afaik not part of reveal.js.*

---

(IMHO one issue for this epic is fine, as long as we don't have implementation plans or lengthy discussions.) So, please share your thoughts on this!

**Comment by ErikMichelson** [comment]
This issue has been split up into several other issues.
