### ISSUE TITLE
Spoiler markdown tag

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#723]
**Is your feature request related to a problem? Please describe.**
Markdown doesn't have a standard tag for soiler blocks. There is a html code snippet, but that's not easy to remember and you can't use other markdown code in html.

**Describe the solution you'd like**
Add a multi line markdown tag like 
```
:spoiler title
Content
:spoiler
```

**Additional context**
This should be pretty easy using the markdown it plugin for containers. (That's the one we already use for alerts)

**Comment by DerMolly** [comment]
I've had a quick look at this and the alertContainer way won't work, I fear. It's a markdown-it-plugin not in our control and only lets you choose the name after the initial `:::` and then add some attributes to the resulting div. But most likely we want to use the already working:

```
<details>
  <summary>Toggle label</summary>
  Toggled content
</details>
```

and need to build our own container plugin, I guess.

**Comment by mrdrogdrog** [comment]
It works very well!
Look at the example on
https://github.com/markdown-it/markdown-it-container

**Comment by DerMolly** [comment]
Okay I didn't saw that and redact my previous comment.
