### ISSUE TITLE
Add support for multicol table cells

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/react-client#724]
**Which part of the project should be enhanced?**
the markdown renderer

**Describe the solution you'd like**

The markdown renderer should support multi-column table cells like this 

```
| Header ||
|--------------|
| 0 | 1 |
```

The `||` syntax seems to be a nice and easy to understand and use. It seems to adopted in some places.

**Describe alternatives you've considered**
Leaving it as is. User would be forced to use:

```
<table>
  <tr>
    <td>One</td>
    <td>Two</td>
  </tr>
  <tr>
    <td colspan="2">Three</td>
  </tr>
</table>
```
instead.

**Additional context**
There is a markdown-it plugin that adds support for this. https://www.npmjs.com/package/markdown-it-multimd-table

**Comment by ccoenen** [comment]
test here on github:

```md
| Header ||
|--------------|
| 0 | 1 |
```

| Header ||
|--------------|
| 0 | 1 |

Or in atom:
![grafik](https://user-images.githubusercontent.com/124909/97842698-52148900-1ce8-11eb-9b7b-6fcbad8ac6ed.png)

This is uncommon syntax that I have never seen before and that is also not supported on any site or in any editor I frequently use (the two above are just quick examples). I would recommend to not include this.

If this is included, I would like to suggest also checking the tradeoff. One can't create a table in markdown without the header column, even if one doesn't need it. So if this plugin makes the following impossible I would be against it:

```md
|||||
|-|-|-|-|
|a|b|c|d|
|e|f|g|h|
```
(quickly huddled together table that does not need a header, but can't function without one)

**Comment by DerMolly** [comment]
I could have sworn I used that syntax before on GitHub or so…
Thanks for the recherche @ccoenen 
I guess we should really think if we want this then.

**Comment by DerMolly** [comment]
I read up on the plugin I linked (again) and it seems the standard they support is based on [MultiMarkdown](https://fletcher.github.io/MultiMarkdown-6/syntax/tables.html) which in turn is based on [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/).

I think we don't want to move away from CommonMark, so until they add support for that, we should probably leave it as is.

What do the others think @hedgedoc/frontend @hedgedoc/backend ?

**Comment by mrdrogdrog** [comment]
Drop it.

**Comment by apfelchips** [comment]
Please add this.
![5281519](https://user-images.githubusercontent.com/6919384/109015353-f1e98e80-76ac-11eb-99e4-d797f607a0d8.jpg)

**Comment by ErikMichelson** [comment]
Multimarkdown's syntax is quite different to HFM in many points. I think that it would rather irritate users to mix up Markdown standards even more.
As users do have the possibility to use colspans by writing raw HTML, I currently see no need for implementing this.

**Comment by SISheogorath** [comment]
Let's not add more markdown flavours in here. The less ways exist to do the same thing, the better. It prevents the number of test cases from growing exponentially

**Comment by mrdrogdrog** [comment]
We don't plan to. We (the frontend devs) had a talk and decided to not implement this.
We would need to create our own plugin for markdown-it, that not only handles multicol tables, but tables at all, because the syntax is not compatible.
