### ISSUE TITLE
Potential security problems through custom css in document.

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#762]
**Description**
Right now the markdown parser doesn't delete custom css. This could to security problems, because you can manipulate the style of the whole page.

**Expected behavior**
One of these:
- Deactivate custom CSS (not prefered, because it can be useful)
- Apply CSS only in renderer (would be nice)
- Turn custom css on / off (not prefered, because you just turn the bug on and off)

**Screenshots**
![image](https://user-images.githubusercontent.com/6124140/99549800-56b09100-29ba-11eb-9720-4ae6cc8949c6.png)

**Comment by mrdrogdrog** [comment]
We could use an iframe or shadow dom, but then we would have to inject the basic stylesheet and use message posting to handle events.
My prefered solution would be to grab the style blocks while transpiling in markdown it and change the containing CSS rules. We can add a prefix to every css selector, so they'll only apply to elements on the inside of the renderer.

**Comment by koraa** [comment]
Thanks for moving the issue!

I would recommend using the iframe solution over rewriting the CSS. There is always a danger of missing rules in CSS and the spec might change. By using an iframe you can disable all possible malicious uses of css wholesale; rewriting css would require having a complete understanding of css which personally I can not say I have.

**Comment by mrdrogdrog** [comment]
My prefered idea (rewriting the css on the fly) would transform 
```
<style>
* {
display: none;
}
</style>
```

into 

```
<style>
.markdown-renderer * {
display: none;
}
</style>
```

This would solve most of the problems, but unfortunately it wouldn't prevent a malicious code from using `position: fixed`.
A shadow dom wouldn't solve this either.

*sigh* seems like we have to take a look at iframe communication.

**Comment by koraa** [comment]
I feel your pain. Last time I did this it was really painful and involved a lot of special stuff. To be most effective there should be some ability to have this on a separate domain (cookies and stuff like that; it's the reason github uses github.io for pages I believe).

I think you may not need to do cross domain communication at all…AFAICR it is possible to access the contents of an iframe with javascript. Same domain shouldn't be a problem at all. Cross domain you would just have to set the right policies…

**Comment by mrdrogdrog** [comment]
Right. I forgot that you can access the inner dom of iframes.
Maybe we can use [React Portals](https://reactjs.org/docs/portals.html) to make it less hacky :thinking: 
Well. It's worth a try.

**Comment by koraa** [comment]
This has as been one of the more pleasurable security related bugs I've filled. Thank you :) :pray:

**Comment by mrdrogdrog** [comment]
You're welcome! :smile:

**Comment by mrdrogdrog** [comment]
Good news: The fix was pretty easy. 
![image](https://user-images.githubusercontent.com/6124140/101961250-9bba9280-3c09-11eb-9a95-75a082194ff7.png)

Bad news: There are...... some minor issues to fix.
![image](https://user-images.githubusercontent.com/6124140/101961288-b1c85300-3c09-11eb-87d6-187d854bc0f0.png)
