### ISSUE TITLE
Pasting 𝆐𝆑 causes 404

### ISSUE THREAD

**Issue by koraa** [hedgedoc/react-client#784]
Pasting "𝆐𝆑" causes a 404 error.

**Comment by mrdrogdrog** [comment]
Please fill out the issue template . Otherwise it's very difficult to help :/

**Comment by koraa** [comment]
Uh, sorry I was offered no issue template?

# What happens?

Pasting "𝆐𝆑 " into a new guest document on https://md.darmstadt.ccc.de/ causes a 404 error to be shown.

# What should happen

No 404 should be shown.

---

I thought this should be easy to reproduce, but when I try it on https://demo.hedgedoc.org/, there is no such error oO

**Comment by koraa** [comment]
Digging a bit more, this all is a result of me trying to type the mezzo forte symbol. I initially tried to enter it with math mode; typing `$f$` and then expanding to `$mf$`. This seems to break math mode somehow; I get various variations of `\(f\)` but not the correct output. Now, when I paste `𝆐𝆑` below, I get a `[Math Processing Error]`. This error won't go away when I delete the `𝆐𝆑`.

https://demo.hedgedoc.org/TJyL8LeMRiGRPzwjCYxE_Q#

This problem cannot be reproduced in chromium for me.

**Comment by mrdrogdrog** [comment]
Oh I'm sorry. It seems like github doesn't like our issue templates anymore. But that's another issue.

I tested your code on demo.hedgedoc.org (which runs on the latest master commit of github.com/HedgeDoc/HedgeDoc) and it didn't crash. Therefore I think, that it's already fixed. As soon as 1.7 is released your instance should also be okay. 

Also: this repository is only for the frontend of HedgeDoc 2.0. We'll only fix bugs that are present in our react client. You can test the new frontend on ui-test.hedgedoc.net.
Every bug that is related to 1.6 or 1.7 belongs into the github.com/HedgeDoc/hedgedoc issue tracker.

**Comment by koraa** [comment]
Thank you for the explanation of repos. The quantity of MD repos is a bit confusing :sweat_smile:

**Comment by SISheogorath** [comment]
Well, we try to make it as straight forward as possible to find the right issue tracker, but it doesn't always work 😉 

![image](https://user-images.githubusercontent.com/8719867/100001889-13905c80-2dc4-11eb-9e4c-0e26753c7303.png)
