### ISSUE TITLE
Share-Dialog: Add positional parameters

### ISSUE THREAD

**Issue by HerHde** [hedgedoc/react-client#789]
**Which part of the project should be enhanced?**

@ErikMichelson proposed a nice feature in #753 which made me think about the "Share link"-dialog.

![image](https://user-images.githubusercontent.com/7630662/100290197-0ff30600-2f7b-11eb-8f32-c178041d2b44.png)

**Is your enhancement request related to a problem? Please describe.**

As we have this dialog already, I would like to use it to visualise (in this case) already implemented related features to make beginners aware of them.

**Describe the solution you'd like**

My proposal is to add optional positional parameters to said dialog to

- include the current anchor (aka the "active" heading, as it is highlighted in the TOC in the current version)
![image](https://user-images.githubusercontent.com/7630662/100289953-6449b600-2f7a-11eb-8e90-5b21ef395539.png)
- and add the current revision (or the unix-timestamp momentum needs to display the revision at which the link was created)

**Describe alternatives you've considered**

For the position I also considered a line number, which would most likely only make sense with a revision, as it is - from my assumption - very prone to change.

**Additional context**

As mentioned Erik gave me some ideas, so I will create separate issues for each to open up discussion.

**Comment by DerMolly** [comment]
While sorting through the issues, we found this issue not relevant anymore. There are already anchor links in the rendered view, that fulfill a similar purpose
