### ISSUE TITLE
Share-Dialog: Add Browser Share-Button

### ISSUE THREAD

**Issue by HerHde** [hedgedoc/react-client#790]
**Which part of the project should be enhanced?**

@ErikMichelson proposed a nice feature in #753 which made me think about the "Share link"-dialog.

![image](https://user-images.githubusercontent.com/7630662/100290197-0ff30600-2f7b-11eb-8f32-c178041d2b44.png)

**Is your enhancement request related to a problem? Please describe.**

A *copy*-button is nice already, but a native *share*-feature would be awesome!

**Describe the solution you'd like**

Display a [share](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) button next to copy, if the browser supports it.

**Describe alternatives you've considered**

Nothing :shrug: 

**Additional context**

As mentioned Erik gave me some ideas, so I will create separate issues for each to open up discussion.

**Comment by ErikMichelson** [comment]
Just for reference: https://caniuse.com/web-share

**Comment by DerMolly** [comment]
Can we target mobile devices specifically?

**Comment by mrdrogdrog** [comment]
Yes. You can check if the function is available. If it is, then use it. If not, then fallback to copy.

**Comment by HerHde** [comment]
I would recommend the method @mrdrogdrog mentioned but add it **additionally** to the copy button
