### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/react-client#816]
**Is your feature request related to a problem? Please describe.**
We often need to display some sort of notification to the user and we currently have no way to put them.
e.g your upload of this image failed

**Describe the solution you'd like**
Include a Notification icon where notifications can be stored and where upcoming notification would be shown.

**Describe alternatives you've considered**
Implement notifications in another way.

**Comment by SISheogorath** [comment]
I would like to avoid to add any form of notification system into an editor. It feels misplaced. Currently failed uploads are invisible, which is obviously not a great way to handle those, but I imagine a little "toast" message should be enough. (Maybe with a link to how to fix it/explaining more details why this might happens. [The Foreman community has something like that](https://projects.theforeman.org/projects/foreman/wiki/ErrorCodes), which is quite awesome for error handling in general.)

Hedgedoc should try to be distraction free. Notifications have the exact opposite intention.

On another note: Looking at other document management systems (Confluence, Nextcloud, …) that implement notifications, I personally never found any of them providing this feature in a useful manner. So, are there already any thought on what, except of error messages, we want to use those for?

**Comment by DerMolly** [comment]
No not really. And we're United in our belobe that this should only be introduced if it has many use cases. Something like this only for upload errors seems needlessly complicated…

**Comment by ErikMichelson** [comment]
When I first had the idea of this feature, I thought of a toast-like way, just that maybe you can open your recently dismissed toasts.
My favored look for such notifications would be like BigBlueButton does them:

![image](https://user-images.githubusercontent.com/52606896/101405511-7e6b8880-38d8-11eb-895f-556a4503df8c.png)

Note that the gray bar at the bottom represents a 10-seconds auto-dismissing.

**Comment by davidmehren** [comment]
A "notification icon" where notifications are stored might become useful if we later™ add more collaboration features like "X has shared note Y with you" or "X has added a comment to your note".

Still, I don't think the place for these "global" notifications would be a good one to show "immediate" feedback for a failed upload. This should be done in a more obvious way, e.g. using some kind of popup or a toast.

**Comment by mrdrogdrog** [comment]
(using toasts and a notification area for stuff like "X has shared Y with you" was the original plan)

**Comment by mrdrogdrog** [comment]
Our intention is (like @ErikMichelson said) to show toasts. These toasts should be shown for a short time. The "notification icon" or "area" is a place where you can see missed or last toasts.
Our notifications are not meant to interrupt the users workflow.
