### ISSUE TITLE
Tags in frontmatter as yaml array

### ISSUE THREAD

**Issue by ptman** [hedgedoc/react-client#872]
**Which part of the project should be enhanced?**

Tags in frontmatter could be specified as yaml array instead of a string with comma separated tags.

**Describe the solution you'd like**

```yaml
---
tags:
  - tag1
  - tag2
```

or

```yaml
tags: ['tag1', 'tag2']
```

**Describe alternatives you've considered**

Currently:

```yaml
tags: tag1, tag2
```

The old syntax could be kept as fallback

**Comment by DerMolly** [comment]
The old syntax needs to be kept for backwards compatibility with currently tagged notes.

**Comment by mrdrogdrog** [comment]
Should we deprecate the old syntax and show a warning? Like for sequence diagrams?

**Comment by ErikMichelson** [comment]
Sounds like a good plan.

**Comment by ErikMichelson** [comment]
Closing as integrated with #874
