### ISSUE TITLE
Add Locales caching to service worker

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#899]
**Which part of the project should be enhanced?**
Service Worker

**Is your enhancement request related to a problem? Please describe.**
While working on #896 I discovered that the current service worker implementation (which is mostly default) doesn't cache our language files, because they are in the "public" directory.

**Describe the solution you'd like**
Add cache entries for the language files.

**Comment by DerMolly** [comment]
This is not applicable anymore, because the language files are not part of the public folder anymore…
