### ISSUE TITLE
Remove PDF-Embedding

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#959]
I propose to remove the pdf embedding.

Reason 1: 
While running the ui-test on my android tablet I found out that the pdf embedding doesn't work. It seems like chrome for android and firefox for android don't have a pdf plugin, which is needed for the embedding. Safari is also very broken. We want to make the new Frontend mobile friendly and this feature won't work.

Reason 2:
The browsers won't allow embeddings without the right http header anymore soon. See https://HedgeDoc.org/faq#why-cant-i-embed-some-pdfs .

Alternatives:
Replace the embedding with pdf.js rendering, but this solution wouldn't last very long. The content would be fetched asynchronously and could be blocked because of CORS.

![Screenshot_2021-01-19-22-20-03-114.jpeg](https://user-images.githubusercontent.com/6124140/105096552-8e65b300-5aa7-11eb-80ae-b212617c25cc.jpeg)

![image.png](https://user-images.githubusercontent.com/6124140/105097180-76426380-5aa8-11eb-8f71-e93fa8dcf6fa.png)

**Comment by davidmehren** [comment]
We *could* get around removing the embedding by leveraging the [image proxy idea](https://github.com/hedgedoc/hedgedoc/issues/95).
If we have an image proxy, we might be able to extend that to also proxy PDFs and therefore get around issues with embed-headers and CORS.

But I'm still unsure if we want such a proxy at all and pretty sure that we won't have one in 2.0. So probably a good idea to remove that feature for now.

> Safari is also very broken.

What the hell is it doing to the page?! 😱

**Comment by mrdrogdrog** [comment]
> What the hell is it doing to the page?! 😱

I guess instead of scrolling it stretches the PDF to the size of embedding 😅

**Comment by mrdrogdrog** [comment]
Anyway. Without a proxy the embedding won't make any sense.

**Comment by DerMolly** [comment]
So then let's remove the pdf embeddings for now.

**Comment by ErikMichelson** [comment]
> If we have an image proxy, we might be able to extend that to also proxy PDFs and therefore get around issues with embed-headers and CORS.

I'm not sure whether that would work at all. Rememeber the original idea was not to implement an own image proxy in the backend server, but rather allow using a third-party proxy server (frontend sends image url to backend, backend generates proxy-url and sends it back to frontend). This solution would rely on pdf support by the third-party server like [camo](https://github.com/cactus/go-camo).
