### ISSUE TITLE
Setting tags from note overview pages

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/react-client#982]
**Is your feature request related to a problem? Please describe.**
Adding tags for multiple notes is hard by now.

**Describe the solution you'd like**
A way to set tags from note overview pages like history or own notes.

**Additional context**
This requires to edit outside the editor, which leads to a implementation of change this note content in backend or fetching all notes where tags were changed from backend, change them and send them back.

**Comment by DerMolly** [comment]
This is not part of the current design document and as we want to introduce [folders](https://github.com/hedgedoc/hedgedoc/issues/1002) anyway, we think it's best to close this issue.
