### ISSUE TITLE
day-mode should be extended to editor

### ISSUE THREAD

**Issue by igalic** [hedgedoc/react-client#984]
**Which part of the project should be enhanced?**

Currently, when toggling between day and night mode, only the toolbar, and preview are changed.
I would like for the actual editor pane to be changed, too.

**Is your enhancement request related to a problem? Please describe.**

On a bright and sunny day, the dark editor is really really hard to use.

**Describe the solution you'd like**

The sun and moon toggle the editor from bright to dark, not just the toolbar

**Describe alternatives you've considered**

alternatively, if people find this offensive to their tastes, i can imagine having different sets of editor styles on the bottom to choose from.

Although i think this solution would be less intuitive and less accessible.

**Additional context**

I am "old" and I'm only getting older, and my eyes are only gonna get worse.

**Comment by davidmehren** [comment]
Moved to the frontend repo so the frontend team can discuss possible changes in 2.0

**Comment by mrdrogdrog** [comment]
If you haven't changed the app theme with the toolbar toggle, then the app(in 2.0) should already follow the browser dark/light mode. Right now the editor theme is detached from the global theme.

IMHO: Of course we can add a linking and it sounds like a good idea, but I don't know if it's a good idea to link them by default.

**Comment by ErikMichelson** [comment]
> alternatively, if people find this offensive to their tastes, i can imagine having different sets of editor styles on the bottom to choose from.

Actually version 2.0 already features multiple theme support. In the editor preferences (wrench icon in toolbar) one can change the editor theme from light to dark and vice-versa. But in fact that's just a toggle for the underlying codemirror theme, this could very easily be extended for more themes.

Besides that I'm with @mrdrogdrog that the app-dark-mode should not be coupled with the editor by default, but one could opt-in for such a feature.
